# ---- ReleaseManagerHelper configuration File ---- #
# To apply changes made to the config file please restart the server.
# Server configurations
Server:
 RootDir: './ServerRoot'        # Static files root
 CertDir: './Cert/cert.pem'
 PkeyDir: './Cert/pkey.pem'
 LoggingLevel: 'DEBUG'         # Logging level, possible values are: 'DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL'
 AccessLogFile: './Logs/webrickServerAccess.log' # Logging Access file
 ServerLogFile: './Logs/webrickServer.log' # Logging file
 Port: 41582                  # Server Port
 ServicesPath:
   Rest: '/services/rest'     # Path (in the Url) to acess the REST services
 MonitorInterval: 5           # Number of secs between cleaning routines
# Session Configurations
Session:
 TimeToLive: 3600             # Time in seconds to kill the session after last interaction
 MaxSessions: 10              # Maximum number of sessions, ignoring master sessions
 LogFile: './Logs/Sessions.log' # Logging sessions file
 Masters:                     # Master sessions, the ip's in this list have special permissions. Can open a session even if the maximum number of sessions as already been reached.
   - '172.16.2.113'
   - '::1'
Tools:                        # Tools are custom to each implementation os the server
 Resolve:
   Deliverables:
     - 'Runbooks'
     - 'Action Tasks'
     - 'Properties'
 Jira:                        # Jira Configurations
  Celfocus:                   # Config for Celfocus Releases
    Site: 'https://celfocusjira.atlassian.net:443'
    ProjectName: 'VFGBNOCCIA'
    Component: 'Automation'   # Componente name
    QueryFields:              # Name of the fields in the query
      status: 'status'
      installationNotes:
        Value: 'customfield_10066'
      summary: 'summary'
      issuetype: 'issuetype'
      assignee: 'assignee'
    NewLineChar: '\n'         # Definition of the new line (or separator) for the text for Confluence and Jira
    DeployStatus:             # List of the Jira status considered ready for release
      - 'Resolved'
      - 'Ready For Deploy'
    Deliverables:             # List of the names of the artifacts expected to be found in the Installation Notes
      - 'Runbooks'
      - 'Action Tasks'
      - 'Properties'
      - 'Gateway Filters'
      - 'Job Schedulers'
      - 'DB Scripts'
  Vodafone:                 # Config for Vodafone Releases
    Site: 'https://cias.jira.agile.vodafone.com:443'
    ProjectName: 'CIAS'
